---
- name: Install Nginx
  hosts: web_servers
  become: yes

  tasks:
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present
        update_cache: true

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create directory /var/www/html
      file:
        path: /var/www/html
        state: directory
        mode: 0755

    - name: Copy HTML file
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html/index.html

    - name: Configure Nginx to serve HTML
      template:
        src: nginx.conf
        dest: /etc/nginx/conf.d/nginx.conf
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
